name: 最近のQiita投稿記事をGistに反映する

on:
  workflow_dispatch:
  schedule:
    - cron: "0 21 * * *" # JST 6:00

jobs:

  build:
    name: Update-gist
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: npm install
      - run: node src/index.js
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 218995479e8a32aafab2b2dcd0c096eb
          QIITA_API_KEY: ${{ secrets.QIITA_API_KEY }}
